// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://viltksxmzontmgtbmvjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpbHRrc3htem9udG1ndGJtdmpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDg5NzksImV4cCI6MjA2NjI4NDk3OX0.boqdL_Y-PGQUfKr3yC9QYnuPmoQc9AXSbhW7llsPim0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);